export { default as DashboardHeader } from "./DashboardHeader";
export { default as DashboardTabs } from "./DashboardTabs";
export { default as CategoriesTab } from "./category/CategoriesTab";
export { default as UsersTab } from "./users/UsersTab";
export { default as BookingsTab } from "./bookings/BookingsTab";
export { default as MessagesTab } from "./messages/MessagesTab";
export { default as ProductManagementTab } from "./products/ProductManagementTab";
export { default as ProductPageTab } from "./product-page-settings/ProductPageTab";
export { default as ContentTab } from "./content-management/ContentTab";
