export { default as DashboardHeader } from "./DashboardHeader";
export { default as DashboardTabs } from "./DashboardTabs";
export { default as CategoriesTab } from "./category/CategoriesTab";
export { default as UsersTab } from "./users/UsersTab";
export { default as BookingsTab } from "./Bookings/BookingsTab";
export { default as MessagesTab } from "./MessagesTab";
export { default as ProductManagementTab } from "./ProductManagementTab";
export { default as ProductPageTab } from "./ProductPageTab";
export { default as ContentTab } from "./ContentTab";
